#!/bin/sh
# Copyright 2001-2011 by eIQnetworks Inc,
# 31 Nagog Park, Acton, MA-01720
# All rights reserved.
#
# This software is the confidential and proprietary information
# of eIQnetworks ("Confidential Information").  You
# shall not disclose such Confidential Information and shall use
# it only in accordance with the terms of the license agreement
# you entered into with eIQnetworks.
# checkAuditLogFileSize.sh -- This script is used to
# check the audit log files rotation period

platform=`uname`
SVERR_FILE=/tmp/eiq_tmp_$$
rm -f ${SVERR_FILE}

status=0

# Following commands must be allowed for sudo user to run this script
# sudo_cmds: grep, read

checkForErrors()
{
	if [ -s ${SVERR_FILE} ]
	then
		if [ $status = "0" ]
		then
			awk '{print "ERROR: " $0}' ${SVERR_FILE}
		else
			cat ${SVERR_FILE} 1>&2
		fi
	fi

	rm -f ${SVERR_FILE}
	echo "[ENDSCRIPT]"
	exit ${status}
}

cmd_prefix=""
if [ $platform = "SunOS" ]
then
        if [ "`which sudo | grep  no`" = "" ]
        then
                cmd_prefix="sudo"
        else
                cmd_prefix="pfexec"
        fi    
else
        if [ -f ./SUDO ]
        then
                cmd_prefix="sudo"
        fi 
fi
case $platform in
  AIX)
	echo "$platform not implemented." 2>> ${SVERR_FILE}
        ;;
  HP-UX)
	echo "$platform not implemented." 2>> ${SVERR_FILE}
        ;;
  Linux)
	file="/etc/logrotate.conf"
	flag=0

	# Check file size of $MsgLog
        if ${cmd_prefix} test -e "${file}"
        then
		${cmd_prefix} cat ${file} 2>> ${SVERR_FILE} | while read line
		do
			res=`echo "${line}" 2>> ${SVERR_FILE} |\
				${cmd_prefix} grep -v "^[ \t]*#" 2>> ${SVERR_FILE} |\
				${cmd_prefix} grep "audit" 2>> ${SVERR_FILE}`
			if [ "${res}" != "" ]
			then
				echo "${line}" 2>> ${SVERR_FILE}
				flag=1
				continue
			fi
			if [ ${flag} -eq 1 ]
			then
				ret=`echo "${line}" 2>> ${SVERR_FILE} |\
					${cmd_prefix} grep -w "}" 2>> ${SVERR_FILE}`
				if [ "${ret}" != "" ]
				then
					echo "${line}" 2>> ${SVERR_FILE}
					break
				else
					echo "${line}" 2>> ${SVERR_FILE} |\
						${cmd_prefix} grep -v "^[ \t]*#" 2>> ${SVERR_FILE}
				fi
			fi
		done
	else
		echo "${file} not found" 2>> ${SVERR_FILE}
	fi
        ;;
  SunOS)
	echo "$platform not implemented." 2>> ${SVERR_FILE}
        ;;
  *)
        echo "Unknown OS"
        ;;
esac

checkForErrors
